name: Fiendish
main: com.nao20010128nao.Fiendish.LemiHell
version: "1.0.0"
api: [1.0.0]
load: STARTUP
author: nao20010128nao
authors: [nao20010128nao]
description: The fiendish-server plugin
website: http://localhost/
depend: [NukkitDepLoader]
